spring.application.name=Spring-Security

spring.security.user.name = rahul
spring.security.user.password = Password

# To make sure the is not cross site access
server.servlet.session.cookie.same-site=strict